kind: pipeline
type: docker
name: bbang-zip-deploy

# Drone CI에서 사용하는 Runner
# Runner가 Docker 기반이어야 MariaDB 접속/Gradle 빌드 가능
steps:

  # 환경 변수 확인 (디버그용)
  - name: debug-env
    image: alpine
    environment:
      DB_USER:
        from_secret: database_user
      DB_PASS:
        from_secret: database_pass
      DB_HOST:
        from_secret: database_host
      DB_NAME:
        from_secret: database_name
    commands:
      - echo "DB_USER=$DB_USER"
      - echo "DB_PASS=$DB_PASS"
      - echo "DB_HOST=$DB_HOST"
      - echo "DB_NAME=$DB_NAME"

  # Gradle Build (테스트 제외)
  - name: build
    image: gradle:7.6-jdk17
    commands:
      - chmod +x ./gradlew
      #- ./gradlew clean build -x test
      - ./gradlew build -x test
      - ls -l build/libs

  # 서버로 JAR 전송
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: server_host         # 서버 IP
      username:
        from_secret: server_user
      password:
        from_secret: server_pass
      port: 9988
      target: /home/wkrud/workspaces/bbang_zip_dev/jar
      source: build/libs/RLA_BBANG_ZIP-0.0.1-SNAPSHOT.jar    # 빌드된 JAR 파일
      strip_components: 2

  # MariaDB 접속 확인
  - name: db-check
    image: mariadb:latest
    environment:
      DB_USER:
        from_secret: database_user
      DB_PASS:
        from_secret: database_pass
      DB_HOST:
        from_secret: database_host
      DB_NAME:
        from_secret: database_name
    commands:
      - echo "DB_USER=$DB_USER"
      - echo "DB_PASS=$DB_PASS"
      - echo "DB_HOST=$DB_HOST"
      - echo "DB_NAME=$DB_NAME"
      - mariadb -h $DB_HOST -u $DB_USER -p"$DB_PASS" --skip-ssl -e "SHOW TABLES;" $DB_NAME

