server:
  port: 8088

spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: "jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # 운영 환경은 update 대신 validate 추천
    show-sql: true             # 운영 환경은 show-sql 끄는게 안전
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html    # Spring Boot 3.x 기준
    operations-sorter: "method"    # 문자열로 명시
    tags-sorter: "alpha"            # 문자열로 명시
    display-request-duration: true

logging:
  file:
    path: /var/log/app/devbbangzip
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    root: DEBUG       # 모든 패키지 로그 출력
    org.springframework: DEBUG
    com.mycompany: DEBUG  # 내가 만든 코드 로그

